chapter2完了しました。
shoujitakahiro/training.frontend pull request #1
Opened 2017-04-10 09:05 UTC by shoujitakahiro

chapter2完了しました。

2017-04-10 10:22 UTC, gkoyama commented on HTML.CSS/01.Basic/chapter2.html
> +<body>
ここから上が参考書の手順と違うようです。
もういちど見直してみて下さい。
たぶん36ページあたりかなぁ

2017-04-10 10:25 UTC, gkoyama commented on HTML.CSS/01.Basic/chapter2.html
> +<h1>一つ上のWed開発を目指すセミナーvol.2   ローカル開発環境の構築　　参加者募集！</h1>
ここの文言が参考書と違いますね。
文言系は手打ちではなくコピペが基本ですね

2017-04-10 10:30 UTC, gkoyama requested changes
修正コメントしましたので宜しくお願い致します。
インデントがついていないので「インデント」で調べてみましょう！
無駄な改行も多いのでインデントも含めて口頭でも説明しますので聞いて下さい。

2017-04-11 09:14 UTC, shoujitakahiro reviewed
test修正完了

2017-04-11 09:26 UTC, shoujitakahiro commented
HTMLの<head>内の内容の修正と<h1>の誤字を修正完了しました。
確認よろしくお願いします。

2017-04-11 12:33 UTC, gkoyama requested changes
OKです！が、
こちらインデントがついていないようですがこれからですか？

2017-04-13 09:33 UTC, gkoyama commented on HTML.CSS/01.Basic/chapter2.html
> +			<li>・受付でメールに添付のQRコードを確認いたします。メール本文をプリントアウトするか、その場でご提示ください</li>
基本的にliもインデントつけますよ

2017-04-13 09:34 UTC, gkoyama approved these changes
OKです！
ここでは修正しなくてもいいですが、liもインデントはつけますね！
次のchapterからは気をつけてください。

2017-04-13 09:53 UTC, shoujitakahiro commented
すみません！次のchapterから気をつけます！確認ありがとうございます。

2017-04-25 00:21 UTC, merged