Chaoter6終了しました。
shoujitakahiro/training.frontend pull request #5
Opened 2017-04-16 23:30 UTC by shoujitakahiro

chapter6終了しました。確認お願いします。

2017-04-17 02:17 UTC, gkoyama requested changes
chapter5の修正指摘にならい修正をお願いします。

2017-04-17 07:57 UTC, shoujitakahiro commented
chapter6の方も修正しました。確認お願いします！

2017-04-17 11:30 UTC, gkoyama requested changes
カンマで区切ったファイル名のものは削除して下さい。

2017-04-18 00:07 UTC, shoujitakahiro commented
余分なファイル削除しました。確認お願いします！

2017-04-18 01:28 UTC, gkoyama approved these changes
OKです！
無駄なスペースや改行がいくつかあるので今後は気をつけてくださいね。

2017-04-25 01:08 UTC, merged